# Generated by Django 4.2.7 on 2026-05-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.CharField(blank=True, help_text='Alternative: Enter image path like /products/image.png', max_length=500, null=True),
        ),
    ]
