# Generated by Django 4.2.7 on 2026-05-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_path',
        ),
    ]
