# Generated by Django 4.2.7 on 2026-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_brand_category_featured_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='brand_banners/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='image',
            field=models.ImageField(max_length=500, upload_to='category_items/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(max_length=500, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='marketingbanner',
            name='image',
            field=models.ImageField(max_length=500, upload_to='marketing/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/'),
        ),
    ]
