# Generated by Django 4.2.7 on 2026-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_brand_banner_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
