# Generated by Django 4.2.7 on 2026-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(default='083001 12996', max_length=100)),
                ('contact_email', models.EmailField(default='gouthamraj@vdgfashion.com', max_length=254)),
                ('store_address', models.TextField(default='61/1,First floor, VDG Fashion Narayana complex, opp. burma hotel, Sivagami Puram, Virudhunagar, Tamil Nadu 626001')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('active_promo_code', models.CharField(default='TREND10', max_length=100)),
                ('active_promo_discount', models.IntegerField(default=10)),
                ('is_store_open', models.BooleanField(default=True)),
                ('facebook_url', models.URLField(default='https://www.facebook.com/fashionvdg/', max_length=500)),
                ('instagram_url', models.URLField(default='https://www.instagram.com/vdgfashion/', max_length=500)),
                ('youtube_url', models.URLField(default='https://www.youtube.com/channel/UCLLKwEMo4FManOeDUO3jaKw', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
