# Generated by Django 4.2.7 on 2026-06-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(default='Trendy looks for every vibe. Stay stylish, every day.'),
        ),
    ]
