# Generated by Django 4.2.7 on 2026-06-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_sitesettings_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
